# Generated by Django 3.2.3 on 2021-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('location', models.CharField(max_length=240, verbose_name='Location')),
                ('size', models.IntegerField()),
            ],
        ),
    ]
