# Generated by Django 3.2.3 on 2021-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='imgurl',
            field=models.CharField(default='url', max_length=255),
        ),
    ]
