# Generated by Django 3.2.3 on 2021-05-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitches', '0002_pitch_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_pitches', to='pitches.pitch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
