# Generated by Django 3.2.3 on 2021-05-26 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(validators=[django.core.validators.MinValueValidator(80000000), django.core.validators.MaxValueValidator(99999999)])),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
