# Generated by Django 3.2.3 on 2021-05-25 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('location', models.CharField(max_length=240, verbose_name='Location')),
                ('imgurl', models.CharField(default='url', max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_pitches', to='pitches.pitch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
